### ISSUE TITLE
Tests not ran due to iphonesimulator error

### ISSUE THREAD

**Issue by wpK** [jspahrsummers/objc-build-scripts#6]
When running cibuild, xctool run-tests returns exit code 1. It's returning 1 because iphoneos is not supported for running tests. But because it's returning 1, $action is then set to build instead of test, so the tests are never ran.

Is this a bug or is there something that needs to be configured differently?

Thanks

**Comment by jspahrsummers** [comment]
It shouldn't be building for `iphoneos` if you're targeting the simulator (it should be `iphonesimulator`). Can you please run the script with `sh -x` and paste the output in here?

**Comment by wpK** [comment]
Running:
`xctool -workspace project.xcworkspace RUN_CLANG_STATIC_ANALYZER=NO -scheme 'project iOS' run-tests`

Results in:
`Test did not run: Testing with the 'iphoneos' SDK is not yet supported.  Instead, test with the simulator SDK by setting '-sdk iphonesimulator'.`

`xctool.awk` says it returns "`1`" if wrong SDK is chosen, and to "try" `iphonesimulator`. But `cibuild` is assuming that if it's the wrong SDK, unit testing shouldn't work all. Would there be any harm in changing it to the following?

``` diff
diff --git a/cibuild b/cibuild
index ae5d49b..ecab2dd 100755
--- a/cibuild
+++ b/cibuild
@@ -120,7 +120,7 @@ build_scheme ()

     local awkstatus=$?

-    if [ "$awkstatus" -ne "0" ]
+    if [ "$awkstatus" -ne "0" ] && [ "$awkstatus" -ne "1" ]
     then
         # Unit tests aren't supported.
         action=build
```

**Comment by jspahrsummers** [comment]
I think the correct fix would be to check for status code `1` first, then set `action=build` only if that check fails.

If you're interested in submitting a fix, can you please open a pull request instead?

**Comment by wpK** [comment]
Just so I'm clear, you're saying to check if awkstatus -eq 1, if so, re-try run-tests with -sdk iphonesimulator. If this is not successful, then set action=build, and continue?

**Comment by jspahrsummers** [comment]
Something like that, yeah. It'll be easier to talk in a pull request, where we can have discussions line-by-line.
