### ISSUE TITLE
Assume clean builds?

### ISSUE THREAD

**Issue by jspahrsummers** [jspahrsummers/objc-build-scripts#9]
On our CI server, at least, we blow away `DerivedData` between every build, so invoking `xctool clean` for each target is basically a waste of time.

Should we just assume that the build will be clean, and that the user should be responsible for cleaning if they want that behavior?

/cc @alanjrogers @joshaber @joshvera @mdiep @robrix @keithduncan

**Comment by joshaber** [comment]
I think it makes sense to leave that to the CI server :+1:
